#!/usr/bin/env python3

import sys
import json
import socket

#Assign host and port
port = 41000
host = "" #WHAT IS IP???

#Creates JSON from array to be sent to server
def create(arr):
				jsonDict = {}

				calName = sys.argv[1]
				jsonDict["calendar"] = calName

				command = arr[2]
				jsonDict["command"] = command

				#Different cases for each command
				if command == "add":
								for i in range(3, len(arr), 2):
												jsonDict[arr[i]] = arr[i+1]

				elif command == "remove":
								jsonDict["identifier"] = arr[3]

				elif command == "update":
								jsonDict["identifier"] = arr[3]
								jsonDict["field"] = arr[4]
								jsonDict["newValue"] = arr[5]

				elif command == "get":
								jsonDict["date"] = arr[3]

				elif command == "getrange":
								jsonDict["startDate"] = arr[3]
								jsonDict["endDate"] = arr[4]
							
				#Bad command, return None
				else:
								print("Error: Unknown Command")
								return None
					
				#Retrun dictionary to be sent to server
				return jsonDict


#Sends data to server using socket and returns what was received
def contactServer(data):
				jsonObj = json.dumps(data) + "\n"

				client = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
				client.connect((host, port))
				client.sendall(jsonObj)
				rec = client.recv(1024)
				client.close()

				return rec

#Invalid input
if len(sys.argv) <= 2:
				print("Error: Not enough arguments")

#Case for add, remove, update, get, getrange commands
elif sys.argv[2] != "input":
				retJSON = create(sys.argv)
				print(retJSON)
				if retJSON != None:
								rec = contactServer(retJSON)

#Case for preloaded JSON file
#JSON file takes form {"commands" : ["add ...", "remove ...", "update...", "getrange...", ...]
elif sys.argv[2] == "input":
				fileName = sys.argv[3]
				with open(fileName, 'r') as f:
								data = json.load(f)
								for item in data["commands"]:
												#adds filler to replace ./mycal and adds calendar name to string
												item = "- " + sys.argv[1] + " " + item
												#makes array out of string
												arr = item.split()

												#Fixes case where a field has a space in it (Ex: "Debartolo 317")
												if arr[2] == "update" and len(arr) > 6:
																arr[5] = " ".join(arr[5:])[1:-1]
																arr = arr[:6]
												
												retJSON = create(arr)
												print(retJSON)
												if retJSON != None:
																rec = contactServer(retJSON)
